finaldie/auto-news

- .dockerignore
- .gitignore
- Makefile
- README.md
- docker/Dockerfile
- docker/Makefile
- docker/docker-compose.yaml
- install.env
Major changes:
- Compatible with MacOS
- Optimize service starting order
- Upgrade airflow to 2.6.2
- Refine Readme
> Support MacOS

- src/af_save.py
- src/ops_article.py
- src/ops_base.py
- src/ops_rss.py
- src/ops_stats.py
- src/ops_twitter.py
- src/ops_youtube.py
Major changes:
- Collect job stats from each step for all the sources
- Display stats when airflow job finished (new pulling DAG)
Upcoming:
- Push stats into the local database and Notion database
> Enhance job stats

- src/af_publish.py
- src/notion.py
- src/ops_collection.py
Major changes:
- Simplified the weekly collection format from 10 pages to 1 page (contains sub 10 pages inside)
Old:
New:
> Enhance weekly collection page format

- src/af_pull.py
- src/af_save.py
Twitter api is unstable recently, make pulling robust
> Robust pulling

- src/af_pull.py
- src/utils.py
Move try-except to utils.prun()
> Refactor af_pull and simplify the code

- .env.template
- README.md
- dags/news_pulling.py
- docker/docker-compose.yaml
- src/af_pull.py
- src/af_save.py
- src/notion.py
- src/ops_article.py
- src/ops_notion.py
- src/ops_reddit.py
- src/ops_rss.py
- src/ops_stats.py
- src/ops_twitter.py
- src/ops_youtube.py
- src/patch_0.py
- src/patch_1.py
- src/patches.py
- src/reddit_agent.py
- src/utils.py
Major changes:
- [New Feature] Support pulling from Reddit source.
- [Enhancement] Patch mechanism not limited to database operation
- [Enhancement] Improve logging messages
- [Fix] Robust Twitter `min_score` parsing
Instructions to upgrade:
- Create Reddit API App to get `client_id` and `client_secret`
- Fill the environment vars in `build/.env` for
* REDDIT_CLIENT_ID
* REDDIT_CLIENT_SECRET
- Then do upgrading: `make upgrade && make stop && make init && make start`
> [Source] Support Reddit source pulling

- src/reddit_agent.py
- src/utils.py
Major changes:
- [New] utils.retry
- [Enhancement] RedditAgent pulling robuster
> [Reddit] Robust subreddits pulling

- .gitignore
- docker/Makefile
- src/notion.py
- src/reddit_agent.py
Major changes
- Fix gallery type subreddit embedding
- Copy requirements-local.txt to `run` folder
> Robust reddit pulling

- src/notion.py
- src/reddit_agent.py
major changes:
- Fix is_image detection
- Enhance the video block assembling
- Enhance gallery images extraction
> [Reddit] Fix and enhance gallery extraction

- dags/sync_dist.py
- docker/Dockerfile
- src/af_dist.py
- src/af_sync.py
- src/reddit_agent.py
Major changes:
- Sync and distribute user rating/embedding to vector database
- [docker] Upgrade airflow to 2.6.3-python3.11 image
> [Reddit] Sync and distribute user rating/embedding to vector database

- src/reddit_agent.py
Major changes:
- Fix page_url if it's short reddit internal url
> [Reddit] Correct page_url

- src/af_pull.py
- src/embedding_openai.py
- src/llm_agent.py
- src/notion.py
- src/ops_reddit.py
- src/ops_youtube.py
- src/reddit_agent.py
- src/utils.py
Major changes:
* Add summary for video post
* Fix video blob in reddit agent
* Limit embedding text length (5k)
* Limit notion pushing max blocks (10)
* Add arxiv loader for reddit post
* Refine output for airflow job
* Stop rank if content length > 2k
> [Reddit] Summarize Video content

- .env.template
- src/embedding_openai.py
- src/llm_agent.py
- src/notion.py
- src/ops_article.py
- src/ops_reddit.py
- src/ops_rss.py
- src/ops_youtube.py
- src/reddit_agent.py
- src/utils.py
Major changes:
- Env var for embedding max length (default 5k)
- Env var for summary max length (default 20k)
- Reddit text blocks keep at most 1 block
- Refine content post web load
- Robust Reddit video loading
- Enable youtube video transcript caching
- Fix arxiv id if version exist
Migration plan:
```bash
make init
```
> [MISC] Add limitation env options for embedding and summary max length

- README.md
- dags/journal_daily.py
- docker/Makefile
- docker/docker-compose.yaml
- src/af_journal_pull.py
- src/af_journal_save.py
- src/llm_agent.py
- src/llm_prompts.py
- src/notion.py
- src/ops_collection.py
- src/ops_journal.py
- src/ops_notion.py
- src/patch_2.py
- src/patches.py
Major changes:
- Introducing **Journal** feature
Upgrading steps:
```bash
make upgrade && make stop && make init && make start
```
> Introducing Journal Feature

- src/llm_prompts.py
- src/notion.py
- src/ops_journal.py
Major changes:
- Refine Journal format
- Skip empty lines
- Add section header if needed
- Correct prompt typo
> [Journal] Refine format

- src/llm_prompts.py
Major changes:
- Enhance Title prompt
> Enhance LLM prompts

- dags/collect_weekly.py
- src/af_collect.py
- src/af_publish.py
- src/notion.py
Major changes:
- Collect Reddit source pages weekly
> [Collection] Collect Reddit source

- src/llm_prompts.py
Major changes:
- Enhance prompts for "TODO", limit the title at most 8 words
> [LLM] Enhance TODO prompts

- src/llm_agent.py
- src/ops_article.py
- src/ops_rss.py
Major changes:
- langchain has a broken changes for WebBasedLoader, here we convert string parameter to a list as a workaround https://github.com/langchain-ai/langchain/issues/11095
- Also robust the loading part when the error occurred
> [Article & RSS] Robust saving phase

- dags/todo.py
- docker/docker-compose.yaml
- llm_const.py
- src/af_todo_pull.py
- src/af_todo_save.py
- src/data_model.py
- src/db_cli.py
- src/llm_prompts.py
- src/notion.py
- src/ops_collection.py
- src/ops_journal.py
- src/ops_rss.py
- src/ops_todo.py
- src/utils.py
- Dedicated DAG for TODO feature, improve the SLA from `1 day` to `30 minutes`
```bash
make upgrade && make stop && make init && make start
```
> [New Feature] Dedicated DAG for TODO list generating, reduce TODO SLA from 1 day to 30minutes

- Makefile
- README.md
- docker/Makefile
Major changes:
- Update README
- Add `build-nocache` Makefile target
> [misc] Update README

- .env.template
- docker/requirements.txt
- src/af_action_pull.py
- src/af_action_save.py
- src/chromadb_cli.py
- src/llama_index_cli.py
- src/llm_agent.py
- src/llm_autogen.py
- src/llm_prompts.py
- src/notion.py
- src/ops_base.py
- src/ops_deepdive.py
- src/ops_journal.py
- src/ops_todo.py
- src/utils.py
- Introducing an experiment feature `Deep dive` which leverage `autogen`: Add Tag `action:deepdive` in the notion page, then write down the deep dive topic in the Takeaways text box
- Improve the summary prompts to keep the numbers as much as possible
- Upgrade `openai` dependency to `1.x`
- Rename DAG `todo` with `action`
- Introducing `llama_index` and `chromadb` for future RAG use case
```bash
make upgrade && make stop && make init && make start
```
> [Experiment] Autogen integration for deep dive feature

- docker/requirements.txt
- Upgrade autogen to 0.2.2
- make upgrade && make stop && make build && make start
> Upgrade deps

- src/llm_autogen.py
- Web Agent scraping url preprocessing
- Arxiv agents will use the past 10 years of papers
- Duckduckgo may block queries if too frequent, either behind a strong proxy or find other solutions
> Robust LLM Agents

- .env.template
- docker/requirements.txt
- src/llm_agent.py
- src/llm_autogen.py
- Integrate Google Gemini LLM, create api key from [Google AI Suite](https://makersuite.google.com/app/apikey), then add `GOOGLE_API_KEY` in `env` file
```bash
make upgrade && make stop && make init && make start
```
> [LLM] Integrate Google Gemini

- src/llm_autogen.py
- src/llm_prompts.py
- Refine default agent parameter
- Refine llm prompt
> [Experiment] Robust Action

- .flake8
- src/llm_agent.py
- src/milvus_cli.py
- src/ops_reddit.py
- src/ops_youtube.py
- Standalone Google Gemini LLM agent
- Fallback to OpenAI if Gemini failed
- Add distance_metric parameter in milvus client (default is L2)
```bash
make upgrade && make stop && make deploy && make start
```
> LLM optimization

- src/ops_audio2text.py
- Optimize the youtube audio download speed and size, super fast download (smaller size) while maintain a good quality of audio
> [youtube] optimize download audio size

- README.md
- docker/requirements.txt
- pyproject.toml
- src/llm_agent.py
- src/ops_base.py
- src/ops_deepdive.py
- src/ops_todo.py
- Update readme
- Introducing `pyproject.toml` file
- Reduce `ops_action` logging volume
- Migrate doc loaders to langchain-community
- Lock langchain versions
- Speed up takeaway pulling speed
> [MISC] Update readme and intro pyproject.toml

- .github/workflow/docker-image.yml
- .github/workflow/python.yml
- For a simple dependency checking
- Build docker image
> Enable github action for package dependency installation

- helm/values.yaml
- src/reddit_agent.py
- Reddit: Robust post extraction
> [MISC] Robust post extraction

- argocd/values.yaml
- docker/requirements.txt
- helm/Chart.lock
- helm/Chart.yaml
- helm/values.yaml
- pyproject.toml
- Upgrade to `Milvus` to 2.4.x
> [Milvus] Upgrade to 2.4.x

- helm/values.yaml
> helm: upgrade base tag to 0.9.9

- .env.template
- .env.template.k8s
- Makefile
- docker/docker-compose.yaml
- docker/portainer/docker-compose.yaml
- helm/values.yaml
- src/af_action_pull.py
- src/af_action_save.py
- src/af_collect.py
- src/af_dist.py
- src/af_journal_pull.py
- src/af_journal_save.py
- src/af_publish.py
- src/af_pull.py
- src/af_save.py
- src/af_sync.py
- src/embedding_agent.py
- src/reddit_agent.py
- Correct the embedding provider for huggingface: hf, hf_inst
- Enhance loggings
> Misc fixes for emb providers

- .env.template
- .env.template.k8s
- Makefile
- docker/docker-compose.yaml
- docker/portainer/docker-compose.yaml
- helm/values.yaml
- src/embedding_hf.py
- src/embedding_hf_inst.py
- src/embedding_utils.py
- Fix HF emb path and apply normalization
- Improve comments
> [emb] Fix hf emb path and apply normalization

- Makefile
- docker/docker-compose.yaml
- docker/portainer/docker-compose.yaml
- helm/values.yaml
- Addressing exceptions during RSS pulling #96
> Release for 0.9.14

- Makefile
- README.md
- docker/docker-compose.yaml
- docker/portainer/docker-compose.yaml
- helm/values.yaml
- Release 0.9.15 tag for helm/k8s
> Release 0.9.15

- LICENSE
> [MISC] update license
