.env.template, src/ops_article.py, src/ops_twitter.py
Motivation: To reduce noises from Notion inbox, introducing server-side per tweet list `min_score` threshold.
Example in `.env`:
```bash
TWITTER_FILTER_MIN_SCORES=AI:4.5,Life:4,Game:5
```
=> [ops.tweet] Introducing per tweet list min_score threshold for server side filtering

src/utils.py
LLM may not be reliable for separating chunks, sometimes
the translation content may be separated by `\n\n` instead of `===`
=> Fix the splitting for summary and translation

.env.template, src/llm_agent.py, src/ops_youtube.py
Use env option `YOUTUBE_TRANSCRIPT_LANGS` to specify the accepted transcript languages
- Default: `en`
- Example: `en,zh`
=> Add env option for YouTube transcript languages

src/ops_twitter.py
LLM is unstable sometimes, it may return no score, assign a default score in this case.
=> [Fix] Assign default score if llm returns no score

src/notion.py, src/ops_base.py, src/ops_journal.py
When no journal input notes, LLM will generate a `hallucination` output
When no journal input notes, create an empty journal note for that day
=> [Journal] Create empty journal note if no input notes

src/ops_youtube.py
- For non-Youtube video pages (maybe wrongly put there), simply ignore.
```bash
[2023-09-26, 17:36:54 PDT] {subprocess.py:93} INFO - [utils.load_video_transcript] cannot find cached transcript, will load it from original video, url: https://tidyfirst.substack.com/p/measuring-developer-productivity?ref=refind, page_id: 49b9b073-a14d-40e9-b573-234c130d9455
[2023-09-26, 17:36:54 PDT] {subprocess.py:93} INFO - Loading Youtube transcript with language en ...
[2023-09-26, 17:36:54 PDT] {subprocess.py:93} INFO - [WARN] LLMYoutubeLoader load transcript failed: Could not determine the video ID for the URL https://tidyfirst.substack.com/p/measuring-developer-productivity?ref=refind
[2023-09-26, 17:36:54 PDT] {subprocess.py:93} INFO - Loading Youtube transcript with language zh ...
[2023-09-26, …
```
=> [Youtube] Robust inbox pages pulling

src/notion.py
Major changes:
- When initial `ToRead` database, create `1` to `5` default options for the `User Rating` column, so users don't bother to create them again. (Notes: users are still able to update/delete anytime by themselves)
=> [notion] Create ToRead database with default options 1-5 for 'User Rating' column

dags/todo.py, src/llm_prompts.py, src/notion.py
Major changes:
- Update default TODO DAG interval from 30 minutes to 60 minutes
- Update Action Item LLM prompts
Upgrade instructions:
- make init
=> Update TODO DAG default interval

.env.template, README.md, docker/requirements.txt
- Update default llm to `undo.env.default_gpt-231106`
- Fix `openai` package version with `0.28.1` at this moment (1.x.x is not backward compatible with langchain)
- Update README
```bash
make init && make stop && make start
```
=> Update default llm to gpt-3.5-turbo-1106

src/utils.py
- Skip loading video transcript from twitch.tv, which leads to an infinite loop
```bash
make upgrade && make stop && make start
```
=> [utils] Skip loading video transcript from twitch.tv, which lead infinite loop

LICENSE, src/notion.py
Ref: #51 
- Fix the compatibility issue for the latest notion: The previous version notion-client 2.0.0 accepted None parameter for children, the latest version 2.2.1 will pass-through and notion backend will return errors. Pass empty array for the case which will compatible with all the versions. e.g.
api.pages.create(
parent=parent,
properties=props,
children=~~None~~[])
- For new users, if failed to deploy, remove `workspace` folder, then `make deps && make deploy && make init && make start`
- For old users, no actions.
=> [Notion] Fix compatibility for the latest notion-client 

.env.template, README.md, src/chromadb_cli.py, src/data_model.py, src/db_cli.py, src/embedding_agent.py, src/embedding_factory.py, src/embedding_hf.py, src/embedding_hf_inst.py, src/embedding_openai.py, src/embedding_openai_0x.py, src/embedding_openai_1x.py, src/ops_milvus.py
- An EmbeddingAgent to manage/switch according to embedding `provider` and `model_name`
- Refine `Redis` cache key with provider and model_name
- Tune the openai failure retry sleep seconds
- Default embedding provider and model name remain as the same, users could change it via the environment vars: `EMBEDDING_PROVIDER` and `EMBEDDING_MODEL`, please see `.env.template` for more details.
=> [Embedding] EmbeddingAgent 

.env.template.k8s, Makefile, README.md, argocd/Chart.yaml, argocd/README.md, argocd/templates/app-auto-news.yaml, argocd/values.yaml, helm/values.yaml, src/ops_reddit.py, src/ops_twitter.py
- [ArgoCD](https://argo-cd.readthedocs.io/en/stable/) deployment
- Robust `ops_reddit`
- Move `NOTION_ENTRY_PAGE_ID` to k8s secret
- Upgrade base image to `0.9.6`
- Tune `Redis` resources to prevent CPU throttling alerts
- Fix `Redis` uri in k8s
- Enable `deepdive` feature by default
=> [ArgoCD] Enable deployment via ArgoCD

.env.template, .env.template.k8s, README.md, helm/values.yaml, src/embedding_agent.py, src/embedding_ollama.py, src/embedding_utils.py, src/milvus_cli.py, src/ops_milvus.py
- [New] Support Ollama as an embedding provider
- [New] A new embedding_utils for easier filtering/sorting relevant candidates according to the metric type
- [Fix] Embedding clean-up compatible with the new Ollama collection naming format
- [Enhance] Configurable `Milvus` similarity metric type: `L2`, `IP`, `COSINE`, ... 
In `build/.env` or `build/.env.k8s`, if we want to switch to Ollama embedding, change the below section
```bash
...
EMBEDDING_PROVIDER=ollama
EMBEDDING_MODEL=nomic-embed-text
...
```
We can chose the one which fit for the purpose:
```bash
MILVUS_SIMILARITY_METRICS=L2
```
=> [Embedding] Support Ollama embedding

.env.template, .env.template.k8s, README.md
- Update default `env` templates:
- openai: use `gpt-4o-mini` as the default
- google: use `gemini-1.5-flash-latest` as the default
=> [MISC] Update env templates with gpt-4o-mini

.github/workflows/docker-compose-deploy.yml, Makefile, docker/docker-compose.yaml, docker/portainer/docker-compose.yaml
- Remove deprecated deployment steps
- Upgrade default image to `0.9.11`
- New github workflow for testing docker compose deploy
=> Fix docker compose deployment

docker/docker-compose.yaml, docker/portainer/docker-compose.yaml
- For Docker (Portainer) environment, the latest MySQL-9 has incompatible with MySQL-8 parameters and prevents the service start, revert and fixes the MySQL version to 8.4.2
- #90
=> docker: Fix mysql database version

docker/Makefile, docker/docker-compose.yaml
- [Fix] Docker compose may not reliable to pick up the env file, workaround to copy the `build/.env` to runtime for `Docker setup`
- #90
=> [docker] Fix docker compose pick env file unreliable issue

docker/requirements.txt
https://github.com/langchain-ai/langchain/commit/28ad244e775610d4826fbfe34c62dba826cf26c9
**Dependency Update:**
- **File:** `requirements.txt`
The application previously encountered the following error during runtime:
```python
TypeError: unsupported operand type(s) for +=: 'dict' and 'dict'
```
This error originated from the `langchain_community/chat_models/openai.py` file, specifically within the `_combine_llm_outputs` method. The root cause was the unsupported operation of adding two dictionaries using the `+=` operator. Updating `langchain` to version `0.3.1` introduces support for nested dictionaries.
---
```markdown
2024-09-26, 17:13:28 UTC] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-09-26, 17:13:28 UTC] {subprocess.py:93} INFO -   File …
```
=> Update langchain-community to version 0.3.1

src/db_cli.py, src/embedding.py, src/embedding_hf.py, src/embedding_hf_inst.py, src/embedding_ollama.py, src/embedding_openai_0x.py, src/embedding_openai_1x.py
The original problem was that
```python
f"{prefix}_embedding_hf_{start_date}".replace("-", "_")
```
was not following the convention that two underscores seperate the `start_date`.
This can be easily refactored into the parent class and made more robust by utilizing the `model_name`, so that we never compare vectors between different embedding models and never find ourselves creating a oversight bug like this again.
=> Fix collection embedding names
